Custom hooks for parsing and propagation
honeycombio/beeline-nodejs pull request #242
Opened 2020-08-06 23:12 UTC by katiebayes

Let's try getting custom hooks configuration out there without the pre-built ones. I'm hoping I've found a good middle ground here.

Need to update some tests and pull some documentation over from my closed PR, and I'll open this up for official review.

**Notes:**
- The instrumentation team would like the custom hook configurations to be base configurations, similar to other hooks
- To keep the scope of the config options exactly the same, the custom hooks will now be attempted right in the LibhoneyEventAPI object; configs will not be returned anywhere else, just the results of the hook
  - This does mean error handling and debugging is being handled in that object as well, rather than in propagation or instrumentation files. I think this is fine.
  - Fallback/existing parsing and propagation will remain where it is
- Since it's going to be easier to break traces as users figure out their customized preferences, and since we have decided to avoid allowing the beeline to break applications, I've incorporated some try/catch patterns and added a whole lot of debug messaging indicating what's going on with tracing (particularly where applying custom hooks)
- We have made a team decision to use the "propagation context" (the object with traceId, spanId, customContext, and dataset) the standard and documented intermediary structure.
  - In case users want to use the existing marshal and unmarshal functions when building custom hooks, and the existing marshal functions expect the "execution context" as input, I have kept the execution field paths as a fallback, prioritizing the new expected structure

2020-08-06 23:13 UTC, katiebayes commented on lib/api/libhoney.js
> +    this.propagationHooks = {
Just making these exact two options available in the below method

2020-08-06 23:14 UTC, katiebayes commented on lib/api/libhoney.js
> +    try {
wrapping this in a `try` so we can catch and log any exceptions. Seemed appropriate since this is a totally custom function

2020-08-06 23:15 UTC, katiebayes commented on lib/api/libhoney.js
> +      const contextKeys = Object.keys(customParsed);
Just being extra thorough here, if I did some fancy custom stuff and accidentally returned `context.spanId` instead of `context.parentSpanId` I'd want to be able to find that quickly

2020-08-06 23:23 UTC, katiebayes commented on lib/api/libhoney.js
> +      const contextKeys = Object.keys(customParsed);
I didn't intend to break on unsupported fields though, just log them on debugging. Handling missing trace ids and such is already handled elsewhere in the beeline.

2020-08-06 23:42 UTC, katiebayes commented on lib/instrumentation/trace-util.js
> +exports.parseTraceHeader = (traceIdSource, req) => {
the functions in libhoney.js will return undefined if there is no custom hook in the configuration. This split allows the config option to stay in the libhoney object and never have to pass here (returning the configuration from those function and applying it here was called out as a concern in the previous PR)

2020-08-06 23:47 UTC, katiebayes commented on lib/propagation/w3c.js
> -function unmarshalTraceContext(header) {
Per w3c spec, we actually should not be checking strictly against version here. Removing this completely and letting the otel parser handle it

2020-08-06 23:49 UTC, katiebayes commented on lib/propagation/w3c.js
> +  return `00-${traceId}-${parentSpanId}-01`;
Just hardcoding this now, there's no reason to store the version elsewhere because we don't need to check against it. Doing the same thing in ruby

2020-08-06 23:55 UTC, katiebayes commented on lib/api/index.js
> +  customParseTraceHeader(req) {
These use slightly different naming because they _only_ return the results of custom hooks. Built-in treatment of parsing and propagation is in the trace_util file

2020-08-06 23:57 UTC, katiebayes commented on lib/api/index.js
> +  getPropagationContext() {
To make it easy for users to access the propagation context format of the current trace when writing custom hooks, I'm exposing this function in the api. It just fetches the current active trace and returns it in propagation context format.

2020-08-07 12:52 UTC, MikeGoldsmith submitted a review, later dismissed
LGTM - just a couple of suggestions about not throwing errors when they are just eaten inside a try/catch.

2020-08-07 12:52 UTC, MikeGoldsmith commented on lib/api/libhoney.js
> +        throw new Error("httpTraceParserHook must return an object");
Instead of throwing an error to the catch statement that just logs and eats it, I think it would be more clear to log here and return.

2020-08-07 12:52 UTC, MikeGoldsmith commented on lib/api/libhoney.js
> +        throw new Error(
As as above, I think it would be better to log and return directly here instead of throwing an error that just gets eaten.

2020-08-07 13:19 UTC, toshok commented on lib/propagation/util.js
> +// getPropagationContext accepts the current execution context async hook
```suggestion
// getPropagationContext accepts the current execution context
```

async_hooks is the facility we use to transmit the context around.

2020-08-07 13:59 UTC, toshok commented on lib/propagation/w3c.js
> +  return `00-${traceId}-${parentSpanId}-01`;
doesn't the otel package have support for generating the header?  feels kinda weird to completely defer to otel when parsing but not when generating it.

2020-08-07 14:02 UTC, toshok commented on lib/api/index.js
> +  customParseTraceHeader(req) {
I don't think this belongs in the exported api.  why export this at the toplevel when any calling code is going to need to fall back?

2020-08-07 14:41 UTC, MikeGoldsmith commented on lib/propagation/w3c.js
> +  return `00-${traceId}-${parentSpanId}-01`;
It does, but requires you to use the OTel HttpTextPropagator implementation instead of exposing a utility function like for `parseTraceParent`.
https://github.com/open-telemetry/opentelemetry-js/blob/master/packages/opentelemetry-core/src/context/propagation/HttpTraceContext.ts#L66

2020-08-07 14:50 UTC, toshok commented on lib/api/libhoney.js
> +    this.propagationHooks = {
I'd say:

1) add a `configure(opts)` in propagation/index.js (ala the one in instrumentation.js)
2) call that method in the toplevel configure method (in lib/index.js).  the code in `propagation/index.js` takes care to deal with the propagation hooks, so we can remove this.
3) the `custom` methods below become.. not custom and just call through to the appropriate methods in propagation/index.js, which do both the custom and fallback behavior.  trying not to bikeshed the names more than "they shouldn't have 'custom' in them" at the moment.
4) move the resulting method bodies up to the toplevel api - there's nothing libhoney-specific about them.

This should hopefully get rid of the circular API calls.  `propagation/` code has no real reason to call through the api at all, and adding things to the toplevel api only to serve our own `propagation/` internals means we're stuck supporting more things.

2020-08-07 14:55 UTC, toshok commented on lib/api/libhoney.js
> +  // return undefined if no custom hook
this goal is leading to a bad API, imo.  we should not be keeping config scope so high.

2020-08-07 16:29 UTC, toshok commented on lib/propagation/w3c.js
> +  return `00-${traceId}-${parentSpanId}-01`;
ahhh, that's really too bad.  not as pretty, but if the spanContext type is less likely to rev than the serialization format, could be something like:

```
  let rv;
  // spanContext below is the otel span context.  presumably a documented type, but maybe not?
  otelPropagator.inject(spanContext, undefined, (_, _, value) => rv = value);
  return rv;
```

2020-08-11 03:32 UTC, katiebayes commented on lib/api/libhoney.js
> +    this.propagationHooks = {
Thanks, just some clarifying questions to try to avoid writing this too many more times :) :
1) what do you think the propagation/index.js function that receives the options should return? Can it just return the two hooks?
2) Can you say specifically what you mean by `takes care to deal with the propagation hooks`, deal with in what way and with what result at that stage? Are you just referring to the fact that it doesn't return all the options, just the hooks, or are you expecting it to do more?
3) And just to make sure, are we saying we're ok with applying the custom hooks directly in the top-level api, or are we expecting that to happen elsewhere?
4) If we're moving the resulting (non-"custom") method bodies to the toplevel api, but we don't want the propagation code to call the api anymore, where are we calling them and how do you envision passing the custom hook (or result of it) to the instrumentations that handle incoming calls? Trace-util could probably pull in the propagation directly instead of via the api.

Thanks for clearing this up! When I have a clearer picture of the end result you're looking for I'm willing to take another stab.

2020-09-01 19:58 UTC, MikeGoldsmith commented on lib/propagation/w3c.js
> +  return `00-${traceId}-${parentSpanId}-01`;
I think for now it's fair for us to use the string literal like we have above and avoid shoe-horning in OTel's W3C `inject` func. We don't really care about the version prefix or trace flags suffix right now, so just passing the in the traceId and parentSpanId is good enough.

2020-09-02 23:35 UTC, katiebayes commented on lib/propagation/index.js
> +
As noted above and in an irt review, configs now pass directly into propagation, bypassing existing dependency flows completely. `setHooks` will run on the initial require along with other config hooks, and `getHooks` will return the hook that was set. An object seemed like it would be overkill here since we just need to set some variables and make them available elsewhere, so I opted for an anonymous function where the hooks will be stored on require and then can be fetched later from the same wrapped function.

2020-09-03 15:32 UTC, katiebayes commented
I'm going to add a few more tests today but this is reconfigured based on combined feedback and is fully functional so I'm opening it up for review!

2020-09-03 15:49 UTC, katiebayes commented on lib/instrumentation/trace-util.js
> +exports.parseTraceHeader = (traceIdSource, req) => {
Update here: Now this function can check for a custom hook before attempting to apply it. I like keeping the function that attempts to apply that config as a separate task rather than cluttering up this one, but the function gets called here. This is nice because we can succinctly access the hook and the function that applies it, do the work here, and apply the default if it's either not set or fails to apply.

2020-09-08 08:28 UTC, toshok requested changes
this is close.  remaining comments are I think just 2 types:

1. copy problems in debug() calls
2. api split ending up with more code on calling side than we need (which requires more api as well)

2020-09-08 08:28 UTC, toshok commented on lib/propagation/honeycomb.js
> +    );
this looks wrong - at best the wrong message.  this looks c&p from w3c.js.  should probably also include `${error}` in the string (same comment applies to w3c.js).

2020-09-08 08:28 UTC, toshok commented on lib/propagation/util.js
> +exports.applyCustomParser = applyCustomParser;
imo (and pretty minor) these next two functions here really warrant their own file, as opposed to being added to the grab bag util.js (maybe hooks.js?)

at any rate, _this_ is where the configure function should live - so that the local bindings for `httpTraceParserHook` and  `httpTracePropagationHook` are accessible.  That way getHooks/customHooks can get dropped, and the code in trace-utils.js simplified.

2020-09-08 19:58 UTC, toshok commented on lib/instrumentation/trace-util.js
> +  }
peeling things back a bit further, and it doesn't have to be in this PR, but the body of `exports.getTraceContext` could be copied over to `propagation` (into a private method), the fallback behavior contained there, and then the above function could go away entirely.  Instrumentation code could call into `propagation.parseFromRequest` (likely through the toplevel beeline API).

2020-09-08 20:35 UTC, toshok commented on lib/api/libhoney.js
> +    this.propagationHooks = {
sorry, just coming back to this now:

1. The configure functions don't return anything - they modify local state for that collection of code.
2. I meant that the code inside of propagation/ is the only piece that needs to know about the hooks.  nowhere else in the beeline does the code need to know about them, that I can tell..
3. not sure about this.
4. we don't want propagation/ code to call into the api, correct.  we _do_ want instrumentation/ code to call into the API, though.  trace-utils.js is really a collection of things that we should figure out how to get rid of/move to the toplevel API - it's a symptom that it's impossible to write a toplevel instrumentation without access to internals.

2020-09-17 14:12 UTC, katiebayes commented on lib/propagation/honeycomb.js
> +    );
yeah definitely a typo, fixed

2020-09-17 14:29 UTC, katiebayes commented on lib/instrumentation/trace-util.js
> +  }
Done, renamed, moved to a "propagation/hooks.js" file. I left the hook argument for the sake of portability, falling back to the configuration. This will make it easier for us to pass in hooks or move it in the future, if that's ok?

2020-09-17 17:01 UTC, katiebayes commented on lib/propagation/util.js
> +exports.applyCustomParser = applyCustomParser;
moved to a propagation/hooks.js file

2020-09-17 17:04 UTC, katiebayes commented on lib/propagation/index.js
> +const configure = (function() {
I don't have a problem with this per se, but global vars are generally considered not great in node, aren't they? Making the change because I'm not interested in digging in on this, but just wanted to put out there the get/set pattern was to keep in line with general best practices for variable scope.

2020-09-17 17:25 UTC, katiebayes commented on lib/propagation/index.js
> +const configure = (function() {
Change made

2020-09-17 21:58 UTC, toshok commented on lib/instrumentation/trace-util.js
> +  }
why would it make it easier?  I'm not sure I understand the possible future use-case.  It's just as easy to change the body of parseFromRequest.

2020-09-21 15:30 UTC, toshok commented on lib/propagation/hooks.js
> -  }
didn't notice this before, but losing this check (and the one from `headersFromContext`) will throw an exception + output a debug() message.  neither of which is terrible, but if the default case remains "user doesn't configure hooks", it's going to be pretty noisy.

2020-09-21 15:31 UTC, toshok approved these changes

2020-09-21 18:52 UTC, katiebayes commented on lib/propagation/hooks.js
> -  }
Fair point. I'll re-add this check based on the now-locally-scope hook.

2020-09-21 20:01 UTC, dsoo approved these changes
👍 Looks good. My only nit is that it might be nice to make some variable names `propagationContext` instead of `context` just because context is so overloaded, but I'm not super strongly opinionated about it.

2020-09-21 20:12 UTC, merged