Add prebuilt interop propagation hooks
honeycombio/beeline-nodejs pull request #253
Opened 2020-09-29 17:43 UTC by paulosman

Adds prebuilt interop propagation hooks so configuration can look like this:

```
const beeline = require("honeycomb-beeline");

beeline({
    httpTracePropagationHook: beeline.w3c.httpTracePropagationHook,
    httpTraceParserHook: beeline.w3c.httpTraceParserHook,
});
```

This also includes a testing suite refactor from a previously closed PR.

For the AWS propagator, this includes a fallback to self (rather than parent) if parent is not present. This PR also includes utility functions for converting an object to a string for propagation, and a string to an object for ingestion. The join characters default to w3c/honeycomb (,, =) but can be overridden

2020-09-29 19:27 UTC, katiebayes commented on lib/propagation/util.js
> +  const keys = Object.keys(obj) || {};
Just peeking at this, realized this should fallback to an empty array, not an empty Object.
```suggestion
  const keys = Object.keys(obj) || [];
```

2020-09-29 19:29 UTC, katiebayes commented on lib/propagation/util.js
> +// function is written to place a joinChar at the beginning of the string
No longer true! Now uses `join()` and will return a string without a leading char. This was done for flexibility on ordering. The needed character is added in the string literal in the marshal function instead.
```suggestion
```

2020-09-30 18:15 UTC, toshok requested changes
a couple of comments with "meh" in them that I care less about.  They'd be clearer imo but I don't really need them.

2020-09-30 18:15 UTC, toshok commented on lib/propagation/aws.js
> +function httpTraceParserHook(req = {}) {
the default parameters on these hooks bug me.  I don't think they help ultimately guard against exceptions being thrown, and instead only change where that exception _is_ thrown.

if req is undefined we'll end up with {}, and `header` below will be undefined.  we'll pass that `undefined` to  `unmarshalTraceContext`, which will throw an exception because the first thing it does is call `header.split`.

why are we trying to support objects that _don't_ have a `headers` field?

barring another reason to have the {} fallback, imo the parser hooks should look like:

```
function httpTraceParserHook(httpReq) {
  return unmarshalTraceContext(httpReq.headers["x-amzn-trace-id"]);
}
```

2020-09-30 18:15 UTC, toshok commented on lib/propagation/aws.js
> +  return { [TRACE_HTTP_HEADER]: exports.marshalTraceContext(context) };
```suggestion
  return { [TRACE_HTTP_HEADER]: marshalTraceContextv1(context) };
```

2020-09-30 18:15 UTC, toshok commented on lib/propagation/aws.js
> +function httpTracePropagationHook(context = {}) {
same here - why do we have a default?  it'll cause a nonsensical string to be returned, something like:

```
Root=undefined;Parent=undefined
```

2020-09-30 18:15 UTC, toshok commented on lib/propagation/aws.js
> +    contextToSend = `;${util.objToString(traceFields, ";")}`;
honestly I'd prefer to have `objToString` take another parameter (`prefix`) that this code passes (the default would be `""` since the other uses don't need it).  That would let us always call `objToString` here, and avoid the duplicate `Object.keys` call here (`objToString` already does it and returns "" if there are none.)

but more meh.

2020-09-30 18:15 UTC, toshok commented on lib/propagation/util.js
> +  if (keys.length > 0) {
Actually, hust remove the keys.length > 0 check and always do the map+join.

2020-09-30 18:24 UTC, toshok commented on lib/propagation/aws.js
> +function httpTraceParserHook(req = {}) {
actually even _that_ will throw an exception in `unmarshalTraceContext` if the header doesn't exist.

second try:

```
function httpTraceParserHook(httpReq) {
  const header = httpReq.headers["x-amzn-trace-id"];
  if (!header) {
    return null; // <- I'm also pretty down on naked returns in functions that also return values.  It's unclear if the intent was to return undefined or if the return value was forgotten.  in functions that return values, all returns should have them.
  }
  return unmarshalTraceContext(header);
}
```

2020-09-30 19:13 UTC, paulosman commented
@toshok took a crack at the "meh" comments (which I agreed with, so went ahead and changed). I'll work on the defaults next.

2020-09-30 20:17 UTC, paulosman commented on lib/propagation/aws.js
> +function httpTraceParserHook(req = {}) {
Yeah, I agree with this - implemented.

2020-09-30 20:18 UTC, paulosman commented on lib/propagation/aws.js
> +function httpTracePropagationHook(context = {}) {
Also made `contextToSend` default to an empty string so we don't get `undefined` at the end of the header. I hope I did that right?

2020-09-30 22:01 UTC, toshok approved these changes
couple of remaining derp moments by yours truly :)

2020-09-30 22:05 UTC, paulosman commented on lib/propagation/util.js
> +  return prefix + fields.join(joinChar);
Derp! Of course. I'll add this guard:

```
if (keys.length == 0) {
  return "";
}
```

2020-09-30 22:19 UTC, merged