Handle pg pool clients
honeycombio/beeline-nodejs pull request #272
Opened 2020-12-23 06:03 UTC by markgaylard

We found an issue when calling the promise returning version of `query` on a pg-pool client. These clients seem to behave a bit differently to both the query method on both `pg.Pool` and `pg.Client`. Both of those create a callback function before the the instrumentation is invoked, but in our case, the callback is created _after_ instrumentation. The upshot is that no callback is passed to the query function instrumented by beeline, so even though the spans are started, they are never finished.

This PR adds a wrapper to promises returned by the query function to fix this issue. It also expands on the tests for the pg instrumentation by asserting that the results returned by the wrapped functions are correct. I've also added a bit to the README file to explain how to run the pg tests.

2020-12-23 06:12 UTC, markgaylard commented
Not sure why circle ci is sad. Doesn't look like it anything from this PR though.

2020-12-23 09:39 UTC, MikeGoldsmith commented
Thanks for the contribution @markgaylard - we'll review and get back to you ASAP.

I'm not sure why CI failed, it looks to be from an unrelated test that timed out. I've triggered the CI to run again.

2020-12-31 00:22 UTC, vreynolds requested changes
<3 the test cases, super helpful! Mostly LGTM, just a couple small asks.

2020-12-31 00:22 UTC, vreynolds commented on lib/instrumentation/pg.js
> +      return error;
`error` needs to be re-thrown here, otherwise the downstream promise chain will receive it in a `then` rather than a `catch`

2020-12-31 00:22 UTC, vreynolds commented on lib/instrumentation/pg.js
> +          return r instanceof Promise && !callback ? promiseWrapper(span, r) : r;
Curious about the `&& !callback` here: I _think_ it might be unnecessary, since `pg` will only return a Promise, [when no callback has been defined](https://github.com/brianc/node-postgres/blob/3f3f1a77c3a87e42df64c5baaa7d42193b0d8529/packages/pg/lib/client.js#L515). Thoughts?

2021-01-02 03:47 UTC, markgaylard commented on lib/instrumentation/pg.js
> +          return r instanceof Promise && !callback ? promiseWrapper(span, r) : r;
Yeah, I can't remember why I added this. I think it might have been while i was testing stuff but it doesn't need to be there so I've removed it.

2021-01-02 03:48 UTC, markgaylard commented on lib/instrumentation/pg.js
> +      return error;
nice catch (see what I did there? 😄 ) 
I've fixed this and updated the tests.

2021-01-04 17:04 UTC, vreynolds approved these changes

2021-01-04 17:10 UTC, merged