TypeScript definitions
honeycombio/beeline-nodejs pull request #308
Opened 2021-02-09 16:40 UTC by antonvasin

As mentioned in #126.

When writing I've used [API.md](docs/API.md) as a reference.

Things I'm not sure about:
* `MetadataContext` seems to deserve stricter type than `any`
* Can context be nested? If so, then we should have some recursive type for it
* `type` and `interface` syntax. Some use both, some use only one, so those things can be very opinionated. Since the project itself is written in plain JS I've tried to write it “default” way
* Couldn't test this with `require` since we're not using it in TS projects at all

2021-02-18 00:46 UTC, vreynolds requested changes
Thank you so much @antonvasin, this will definitely be appreciated!

I did my best to capture any discrepancies, combing through the code. As you can see, the docs are not super comprehensive, unfortunately.

Do you have bandwidth to address the changes?

2021-02-18 00:46 UTC, vreynolds commented on lib/types.d.ts
> +export interface BeelineOpts {
Additional optional configurations:
- samplerHook
- presendHook
- disableInstrumentation
- express:
  - userContext
  - traceIdSource
  - parentIdSource
- fastify
  - userContext
  - traceIdSource
  - parentIdSource
- mongodb
  - includeDocuments

2021-02-18 00:46 UTC, vreynolds commented on lib/types.d.ts
> +import http from "http";
I'm getting a linter error here: `Module '"http"' has no default export.` Perhaps `import * as http from "http"` or just `import {IncomingMessage} from "http"`?

2021-02-18 00:46 UTC, vreynolds commented on lib/types.d.ts
> +  customContext?: TraceContext;
I believe `customContext` here would be a `MetadataContext`. Is that the nested context question you had?

2021-02-18 00:46 UTC, vreynolds commented on lib/types.d.ts
> +type HttpTraceParserHook = (req: http.IncomingMessage) => TraceContext;
There's a use case for creating custom trace parser/propagator hooks. Can we export `HttpTraceParserHook` and `HttpTracePropagatorHook` types?

2021-02-18 00:46 UTC, vreynolds commented on lib/types.d.ts
> +  getTraceContext(): TraceContext;
After digging through the code, I noticed that there's 2 "context" representations. There's the `TraceContext` as well another one (ExecutionContext??), used in the [async tracker](https://github.com/honeycombio/beeline-nodejs/blob/b6cf0963cbbc7effdaff77b40d8772ff5ed2e18a/lib/api/libhoney.js#L110), which is what's returned from `getTraceContext()`:
```
{
  id?: string;
  traceContext?: MetadataContext;
  stack?: Span[];
  dataset?: string;
}
```

This exercise is certainly highlighting some loose ends in the interface!

2021-02-18 00:46 UTC, vreynolds commented on lib/types.d.ts
> +    dataset?: string
`startTrace` takes `propagatedContext?: MetadataContext` as a final argument, and also it looks like return type is `Span | undefined` based on this [line](https://github.com/honeycombio/beeline-nodejs/blob/b6cf0963cbbc7effdaff77b40d8772ff5ed2e18a/lib/api/libhoney.js#L131)

2021-02-18 00:46 UTC, vreynolds commented on lib/types.d.ts
> +  startSpan(metadataContext?: MetadataContext): Span;
`startSpan` returns `Span | undefined` based on this [line](https://github.com/honeycombio/beeline-nodejs/blob/b6cf0963cbbc7effdaff77b40d8772ff5ed2e18a/lib/api/libhoney.js#L131)

2021-02-18 00:46 UTC, vreynolds commented on lib/types.d.ts
> +  finishSpan(event: Span): void;
`finishSpan` takes `rollup?: string` as a second argument

2021-02-18 00:46 UTC, vreynolds commented on lib/types.d.ts
> +  withSpan<F>(fn: SpanFn<F>, rollup?: string): F;
Is the second `withSpan` line intentional? I think metadataContext is non-optional: https://github.com/honeycombio/beeline-nodejs/blob/b6cf0963cbbc7effdaff77b40d8772ff5ed2e18a/lib/api/index.js#L118

2021-02-18 00:46 UTC, vreynolds commented on lib/types.d.ts
> +  marshalTraceContext(ctx: TraceContext): string;
Based on above comment about the 2 context representations, all the marshal functions are written to work with both, so I think they would take `TraceContext | ExecutionContext` as an argument.

2021-02-18 00:46 UTC, vreynolds commented on lib/types.d.ts
> +  unmarshalTraceContext(ctx: string): TraceContext;
All the unmarshal functions may return `undefined` in case of an error.

2021-02-18 00:46 UTC, vreynolds commented on lib/types.d.ts
> +    unmarshalTraceContext(ctx: string): TraceContext;
Tiny pick: `unmarshalTraceContext` argument is a `honeycombTraceHeader` not a `ctx`

2021-02-18 00:46 UTC, vreynolds commented on lib/types.d.ts
> +    unmarshalTraceContext(traceparent: string, tracestate: string): TraceContext;
`tracestate` can be optional

2021-02-18 00:46 UTC, vreynolds commented on lib/types.d.ts
> +  TRACE_HTTP_HEADER: string;
`TRACE_HTTP_HEADER` is deprecated: `/** @deprecated this constant will be removed in the next major release. Please use honeycomb.TRACE_HTTP_HEADER instead. */`

2021-02-18 00:46 UTC, vreynolds commented on lib/types.d.ts
> +  httpTraceParserHook: HttpTraceParserHook;
I don't believe there's a top-level `httpTraceParserHook`/`httpTracePropagationHook` exported. I think you already defined all of them under the 2 namespaces (honeycomb, w3c, aws)

2021-02-18 00:51 UTC, vreynolds commented
Oh, as far as your questions:
- MetadataContext: I agree, it would be nice to nail down exactly the attribute types, but I think at this point, I'd rather err on the side of permissive/backwards-compatible way (aka `any`)
- nested context: I think I addressed that in the review comment, but let me know if you meant something else
- type and interface: LGTM
- I used `require` to import the beeline in my test TS service

2021-02-20 17:41 UTC, antonvasin commented
Thanks for the feedback.

> Do you have bandwidth to address the changes?

Sure, I'll look into them.

2021-03-03 16:48 UTC, joerayme commented on lib/types.d.ts
> +export interface TraceContext {
I believe this can also have an optional `source` attribute, [for example](https://github.com/honeycombio/beeline-nodejs/blob/28a176981e38a23d034d4a9e7a7f99b15daa18c8/lib/instrumentation/trace-util.js#L26)

2021-03-14 09:43 UTC, DavidS commented
see https://github.com/honeycombio/libhoney-js/pull/90 for a similar effort.

2021-03-15 11:55 UTC, antonvasin commented on lib/types.d.ts
> +  httpTraceParserHook: HttpTraceParserHook;
Yeah, my bad. Removed those definitions.

2021-03-15 11:55 UTC, antonvasin commented on lib/types.d.ts
> +  TRACE_HTTP_HEADER: string;
Added `@deprecated` to this

2021-03-15 11:55 UTC, antonvasin commented on lib/types.d.ts
> +    unmarshalTraceContext(ctx: string): TraceContext;
Renamed this

2021-03-15 11:55 UTC, antonvasin commented on lib/types.d.ts
> +  marshalTraceContext(ctx: TraceContext): string;
I've defined `MarshallableContext` type for those and updated argument type.

2021-03-15 12:06 UTC, antonvasin commented
I've updated this MR with comments above. Took me a while, sorry.

2021-03-29 02:23 UTC, vreynolds approved these changes

2021-03-29 02:28 UTC, vreynolds commented
@antonvasin same here, took a while to come back to this. The changes look good to me 👍 Do you mind resolving the package conflict?

2021-04-06 20:02 UTC, merged