Whatwg url object fix
honeycombio/beeline-nodejs pull request #324
Opened 2021-03-25 19:59 UTC by wcgallego

2021-03-26 01:13 UTC, wcgallego commented
So this should hopefully fix issues with some whatwg urls not being handled correctly by the beeline wrapper code.

I'd ask for nitpicking/fine toothed comb when walking over this as I'm no node pro.

As for tests, I cleaned up the existing ones but was a bit shaky on adding more. I have some half baked ones I was making https.request and http.request calls with that I can gist if it'll help

2021-03-31 19:10 UTC, paulosman commented
Thanks @wcgallego ! We'll review this ASAP.

2021-03-31 19:12 UTC, wcgallego commented
Great, ty! We're pointing to this now in our production environment after some local testing, so if anything goes sideways I'll bring it up here

2021-03-31 23:32 UTC, paulosman commented
> As for tests, I cleaned up the existing ones but was a bit shaky on adding more. I have some half baked ones I was making https.request and http.request calls with that I can gist if it'll help

That'd be great! On first pass, I was going to ask to include some tests - a gist would be helpful!

2021-04-01 11:25 UTC, wcgallego commented
No prob, here's a gist (appropriate HC values where noted):
https://gist.github.com/wcgallego/bc8b40cf9ffa0980a1b7af4f74374e21

2021-04-01 22:16 UTC, vreynolds requested changes
Wheew there's a lot here, appreciate you taking a stab at it!

I added a test suite for http, mostly to wrap my head around all the cases, but figured might as well add it to the PR. You can see that there's some failures there:
- the missing slash on the event URL is a bit concerning, because that would change existing behavior, and I'd like to avoid that, so we can do a non-major release
- none of the URL type calls are passing -- could certainly be the test setup, but I tried to keep it simple.
- there's some test pollution going on, we'll need to look into it later, but essentially if you can get the `argument permutations` describe to pass, the other tests will pass (based on my local testing outside this PR)

2021-04-01 23:39 UTC, wcgallego commented on lib/instrumentation/http.js
> +        asyncSpanURL = _url;
This is a great question! Nothing for certain in any of this comment.

If _url were an object, it would be a URL one, as I don't think WHATWG-URL accepts two plain url objects.

In that case, I also don't think you can do an URL object *and* a plain object together, which would be necessary to make it such, as it doesn't set _url to an object if there's only one arg passed in.

All that said, we could be defensive in the programming and typecheck it in this conditional chain

2021-04-01 23:41 UTC, wcgallego commented on lib/instrumentation/http.js
> +        asyncSpanURL = 'http://' + (combinedOptions.hostname || 'localhost')
hrm, not 100% following. if it's an https request I would assume the protocol should always bee https and similarly for http.request. They're hardcoded for their respective files which is subtle, admittedly.

Why would you want the asyncSpanURL to have an https protocol if called by the http.request method, or vice versa?

2021-04-01 23:43 UTC, wcgallego commented
Yeah, the tests were a little beyond me and was hoping the Honeycomb crew could carry that over the line. The submitted gist all work, so while I can't guarantee it, I would venture to assume it's the set up of the tests and not the change itself that's causing issues.

The dangling slash is reasonable and if I can help avoid a major release to help y'all, I'm down to try that. Lemme start small and just fix that, but if anyone can jump in earlier, that'd be appreciated!

2021-04-01 23:50 UTC, wcgallego commented
Sorry to spam - one last thing about trailing slash. 

We make a call to `http://google.com` (no trailing slash) on line 30 of the https test:
https://github.com/honeycombio/beeline-nodejs/blob/d18a284cc44d6ef42d2ea5688afbad9d7283f5cb/lib/instrumentation/https.test.js#L30

I would then assume the trace url should match that more closely - no trailing slash in the requested url, so the url sent in the traced span shouldn't have one either.

Is there a good reason that's not the case in the tests before this PR and it should stay that way?

2021-04-24 01:41 UTC, vreynolds commented
Finally had a chance to take a look at this again. Oh boy, is this stuff gnarly 😢 There's more permutations than I thought:

```
function get(options: RequestOptions | string | URL, callback?: (res: IncomingMessage) => void): ClientRequest;
function get(url: string | URL, options: RequestOptions, callback?: (res: IncomingMessage) => void): ClientRequest;
```

So both url and options can be instance of URL.

Furthermore, when we apply the combinedOptions to the original function, the options override the first url parameter, hence the connection refused error in test (it's trying to connect to default port 80). I think we need to go back to building out a truly combined options (and dropping the first url parameter), so we can add on the propagation headers.

WRT to trailing slash, looks like existing behavior came from using url.parse on a string url param, which adds a trailing slash, even when the original string didn't have one. I don't think there's a strong reason to keep this behavior philosophically, it really boils down to backwards-compatibility.

Will try to take a look at this again when my brain recovers. lolsob

2021-05-26 23:05 UTC, vreynolds commented
@wcgallego sorry for the slow turnaround on this. I tried again to massage this, and it's proving a bit of a whack a mole. I ended up copying the test suite over to a new branch, and adding an if block for the URL case. I liked your approach - it makes this code easier to reason about, but I think a more strategic surgery might be the way to get this moving.

Can you check out #361 and see if that would work with your test scenarios?

2021-06-23 21:18 UTC, vreynolds commented
Closing this since merging #361 . Thank you for taking a stab at it!

2021-06-23 21:18 UTC, closed without merging