Use collection names for MongoDB spans.
honeycombio/beeline-nodejs pull request #395
Opened 2021-07-05 22:20 UTC by djanowski

It's much more useful to see `users.findOne` than `collection.findOne`. I'll update tests once/if https://github.com/honeycombio/beeline-nodejs/pull/393 is merged.

2021-07-13 13:05 UTC, MikeGoldsmith commented
Hey @djanowski - thanks again for your contributions.

I think this looks good, but would like to see a test to verify that the collection name is being populated in the event name as expected.

2021-07-13 13:07 UTC, MikeGoldsmith requested changes
Hey @djanowski - thanks again for your contributions.

I think this looks good, but would like to see a test to verify that the collection name is being populated in the event name as expected.

2021-07-27 18:50 UTC, djanowski commented
#393 adds the scaffold for MongoDB tests. Once that PR is merged, this PR will break the tests, and I'll update them. Thanks!

2021-08-09 12:35 UTC, MikeGoldsmith commented
We're going to close this for now as this and #393 have had low activity. Feel free to re-open if it’s still relevant.

2021-08-09 12:35 UTC, closed without merging