Migrate and update example from examples repo
honeycombio/beeline-nodejs pull request #494
Opened 2021-11-09 19:35 UTC by JamieDanielson

## Which problem is this PR solving?

- migrates node-tracing example from examples repo

## Short description of the changes

- updated to use local beeline code as dependency, which is installed and linked with `npm run setup`
- removed deprecated methods in favor of new, e.g. `beeline.honeycomb.marshalTraceContext`
- added notes around using analysis file, and renamed `wall.js` to `app.js`
- set everything to run as `npm start` and `npm start-all` depending on whether just using one or both services

2021-11-10 04:01 UTC, vreynolds approved these changes

2021-11-12 19:02 UTC, JamieDanielson commented
@vreynolds requesting a re-review as I tore out some of the original example and added some new stuff in.

2021-11-12 23:09 UTC, vreynolds requested changes

2021-11-12 23:09 UTC, vreynolds commented on examples/node-tracing/app.js
> +const HONEYCOMB_DATASET = `${process.env.HONEYCOMB_DATASET}` || "tracing-example";
string interpolation results in a literal string "undefined" when there's no env var

```suggestion
const HONEYCOMB_DATASET = process.env.HONEYCOMB_DATASET || "tracing-example";
```

2021-11-12 23:09 UTC, vreynolds commented on examples/node-tracing/app.js
> +const SERVICE_NAME = `${process.env.SERVICE_NAME}` || "wall";
```suggestion
const SERVICE_NAME = process.env.SERVICE_NAME || "wall";
```

2021-11-12 23:09 UTC, vreynolds commented on examples/node-tracing/app.js
> +const HONEYCOMB_API_KEY = `${process.env.HONEYCOMB_API_KEY}` || "abc123";
```suggestion
const HONEYCOMB_API_KEY = process.env.HONEYCOMB_API_KEY || "abc123";
```

2021-11-15 18:00 UTC, vreynolds approved these changes
✨🍾✨

2021-11-15 19:20 UTC, merged