Further improvements to typescript types
honeycombio/beeline-nodejs pull request #509
Opened 2021-12-08 18:10 UTC by glenjamin

## Which problem is this PR solving?

Fixes #507 

## Short description of the changes

* expose `_apiForTesting`
* provide event type to sample/presend hooks
* include the Span type for SpanFn (previously this typed `span` as `any`)

2021-12-08 18:11 UTC, glenjamin commented
> I don't mind exposing the libhoney.Event type here though as an extra layer doesn't really give us much other than stopping people doing silly things 😄 .

I was going to do this, but then I realised libhoney doesn't actually have any typescript types - so I just made a small interface inline here.

2021-12-09 23:11 UTC, glenjamin commented on lib/types.d.ts
> +  type SpanFn<F> = (span: Span) => F;
The previous signature is just wrong, SpanFn is only ever called with a single span argument

2021-12-09 23:12 UTC, glenjamin commented on lib/types.d.ts
> +    bindFunctionToTrace<T extends Function>(fn:T): T;
Hrm, good spot! I think a variadic any => any func does the same thing without the class gotcha

2021-12-09 23:14 UTC, glenjamin commented on lib/types.d.ts
> +    _apiForTesting(): {
In practice this is only used by tests (as the name neatly hints at).

Without this hint tests written in typescript require an any cast and lose type safety on the mock events they assert on.

The tests in this module use it to test instrumentation - and we're using it in our codebase in cases where the instrumentation is important enough that we want to assert on it

2021-12-09 23:15 UTC, glenjamin commented
Thanks for the quick review! I'll make the uncontroversial PR updates tomorrow.

Would you prefer additional commits to address or amending the original?

2021-12-10 09:40 UTC, glenjamin commented on lib/types.d.ts
> +  export type MetadataContext = Record<string, unknown>;
The linter was warning about the use of `any`, as this is only used as an input type. I believe downgrading to `unknown` should be safe - but it could cause issues for consumers if anyone is using the `MetadataContext` type directly and trying to read from the values

2021-12-10 19:18 UTC, JamieDanielson requested changes
Thanks @glenjamin ! LibhoneyEvent looks good, and I added a few more comments based on the updates.

2021-12-10 19:18 UTC, JamieDanielson commented on lib/types.d.ts
> +    runWithoutTrace<T extends AnyFunction>(fn:T): T;
Actually, reviewing `runWithoutTrace`, it seems like this may not have the same signature as `bindFunctionToTrace`. 

`bindFunctionToTrace` wraps the function so the return type is the same as the argument type... whereas `runWithoutTrace` runs the function, so the return type is different from the argument type.

2021-12-10 19:18 UTC, JamieDanielson commented on lib/types.d.ts
> +  type SpanFn<F> = (span: Span) => F;
Okay that makes sense, thanks!

2021-12-10 19:18 UTC, JamieDanielson commented on lib/types.d.ts
> +    _apiForTesting(): {
True, I guess `apiForTesting` is technically already exposed and this is just exposing the types. Since it is a private method and has "testing" in the name, that is hopefully enough for end users but since we're not looking to make many further changes here, I think it'd be ideal to have a JSDoc for a disclaimer on this not being used in production. Can you add that to this PR?

2021-12-10 19:18 UTC, JamieDanielson commented on lib/types.d.ts
> +  export type MetadataContext = Record<string, unknown>;
It's true that `any` isn't ideal, and we've thought about it a bit in the past but it may be best to keep it as-is for now since it is so widely used. Potentially at a later point it may be worth revisiting, but in the meantime let's keep the warning there.

2021-12-10 19:33 UTC, glenjamin commented on lib/types.d.ts
> +    runWithoutTrace<T extends AnyFunction>(fn:T): T;
oh! I'll check these and fix them.

I'm starting to wonder if there should be some "tests" of some sort for this definition file

2021-12-10 19:34 UTC, glenjamin commented on lib/types.d.ts
> +    _apiForTesting(): {
JSDoc is a good shout, I'm also tempted to copy the docs from API.md into these types so they appear as hints under use - which should work on any IDE which uses typescript under the hood even if the consumer is writing javascript (eg VSCode)

2021-12-14 19:15 UTC, JamieDanielson approved these changes
Awesome, thanks @glenjamin!

2021-12-14 19:16 UTC, merged