Add Environment & Services support
honeycombio/beeline-nodejs pull request #551
Opened 2022-03-16 19:26 UTC by MikeGoldsmith

## Which problem is this PR solving?
Adds E&S support by ensuring service name and dataset are configured correctly for both classic and non-classic API keys. Classic keys use the dataset and non-classic uses the servicename for target dataset.

The beeline also now assigns a default service name based on the API key provided. Classic gets "nodejs" and non-classic gets "unknown_service:{process-name}" where process name is the node process.name name if assigned and falls back to "nodejs" is it cannot resolve one.

The Beeline now applies the following defaults:
| Property | Classic | Non-classic |
| - | - | - |
| service name | unknown_service:{process.name\|nodejs} | unknown_service:{process.name\|nodejs} |
| dataset | nodejs | unknown_service |

Note, I selected to not update the default dataset from `nodejs` to `beeline-nodejs` as this would be a break change for anyone relying on that now. We can make the change in the next major release.

- Closes #550 

## Short description of the changes
- Update libhoney.configure to detect and apply defaults for service name and dataset
- Warn on missing API key, dataset (classic) and service name (non-classic)
- Update tests and add extra tests for default service name and dataset
- Don't propagate dataset in Honeycomb propagation implementation (w3c doesn't propagate dataset field)

2022-03-16 19:57 UTC, JamieDanielson reviewed
Confirmed this works with EGS... but it looks like we still need to add `service.name`.

Maybe add something like `exports.TRACE_SERVICENAME = "service.name";` in `schema.js`, and `[schema.TRACE_SERVICENAME]: opts.serviceName,` in `libhoney.js`?

2022-03-16 22:03 UTC, JamieDanielson requested changes

2022-03-16 22:22 UTC, vreynolds commented on lib/api/index.test.js
> +test("libhoney default config - non-classoc", () => {
```suggestion
test("libhoney default config - non-classic", () => {
```

2022-03-17 13:26 UTC, MikeGoldsmith commented on lib/api/libhoney.js
> +      opts.serviceName.trim();
Fixed in [c474904](https://github.com/honeycombio/beeline-nodejs/pull/551/commits/c474904330ceef73228b4416cfda3bde4fdc5733) 😄

2022-03-17 16:38 UTC, JamieDanielson approved these changes
Nice! As we chatted about, can consider using Template literals for the string concatenation, but otherwise this looks great.

2022-03-17 16:43 UTC, JamieDanielson approved these changes
🚀

2022-03-17 16:45 UTC, merged